### ISSUE TITLE
[1.16.4] Bone Hoe Crash

### ISSUE THREAD

**Issue by Salamance73** [stal111/Forbidden-Arcanus#118]
Hi I used a bone hoe (enchanted with eternal stella so its indestructable) on a piece of overgrown stone (from Oh the Biomes You'll Go) and got a crash. I'm playing with other mods on All the Mods 6.

[https://pastebin.com/XMG2CGcr](url)

Edit: The crash seems to be from tilling something that cannot be tilled. I attempted it again with regular dirt and it tilled it on the first click but on the second click I got the crash again.

**Comment by Salamance73** [comment]
Well, good news is that it did bone meal the ground and make some grass, but the crash there was unexpected.

**Comment by AbyssalRook** [comment]
Getting the same error with the same item, though I was using it on standard wheat on standard tilled soil. Not sure if this makes any difference, but it DOES grow the wheat before it crashes. When you load back in, the plant has grown.

**Comment by TigerWalts** [comment]
Another crash report for this.

- https://pastebin.com/n7EgcJg9

Here's the line causing the crash:

https://github.com/stal111/Forbidden-Arcanus/blob/722e34d4a1f3bb77ca1243ea330b00bb851d5eee/src/main/java/com/stal111/forbidden_arcanus/item/BoneHoeItem.java#L34

It errors because on a client connected to a server, `ItemUseContext,getWorld()` is returning a `net.minecraft.world.client.ClientWorld`. While `ClientWorld` likely shares a parent class with `net.minecraft.world.server.ServerWorld` it cannot be cast to it directly.

It only reaches this code if the block type isn't in `net.minecraft.item.HoeItem.HOE_LOOKUP`. 

The call to `BoneHoeItem.onItemUse()` is triggered by an ASM hook in Apotheosis:

https://github.com/Shadows-of-Fire/Apotheosis/blob/a457c5f778a8fb54445447f91c6b2abfed73fd3e/src/main/java/shadows/apotheosis/deadly/asm/DeadlyHooks.java#L118-L123

It looks like this hook is being removed in the next release of the mod. Though any other mod could potentially trigger the crash.

**Comment by ClaudiusMinimus** [comment]
I guess this is a me-too moment.

Adding the bone hoe to a quest in my mod pack and when I tested to the client crashed

Minecraft 1.16.5
F&A 16.2.0-beta-3
Forge 36.1.0

https://paste.ee/p/tNZun

**Comment by ClaudiusMinimus** [comment]
The bone hoe still crashes the client

Minecraft 1.16.5
F&A  16.2.0-beta-4
Forge 36.2.0

https://paste.ee/p/bftQf

**Comment by stal111** [comment]
Bone Tools have been removed in 16.2.0.
