### ISSUE TITLE
Tetra items in the Indestructible Blacklist Causes Crash on Startup

### ISSUE THREAD

**Issue by Crazydude323** [stal111/Forbidden-Arcanus#128]
Forbidden & Arcanus (forbidden_arcanus) has failed to load correctly
§7com.electronwill.nightconfig.core.io.ParsingException: Invalid value tetra:modular_sword - Expected the boolean value true.

This is the error, got it after putting the various items from Tetra into the blacklist for the indestructible enchantment. I don't know if this causes a crash with any item in the blacklist, or just Tetra items, but it's certainly a problem.

**Comment by Vaelzan** [comment]
Can you please upload and link the config file?

(I'm not a developer on this mod, but since I can see the source code and have dealt with config issues before I might be able to either help you or provide additional information for the issue report)

**Comment by Crazydude323** [comment]
Here you are. I changed it to a .txt because github said it doesn't support .toml files, but the content is the same.

[forbidden_arcanus-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/5837825/forbidden_arcanus-client.txt)

**Comment by Vaelzan** [comment]
@stal111 The configuration for this is in the client config anyway instead of the common or server config, which is a bug on its own outside of OP's issue (but related, so not filing a new issue for it).

https://github.com/stal111/Forbidden-Arcanus/blob/1.16/src/main/java/com/stal111/forbidden_arcanus/config/EnchantmentConfig.java

I haven't had a chance to dig deeper into why the config is breaking in the first place though.
