### ISSUE TITLE
[Bug] CTD with Edelwood Magma Cube Bucket (Valhelsia 3.1.8a)

### ISSUE THREAD

**Issue by WhatThePuckPT** [stal111/Forbidden-Arcanus#144]
Crash that happens when a Magma Cube is picked up with an Edelwood Bucket, not corrently known if restricted to Valhelsia 3.1.8a or the mod alone - one of the Valhelsia devs recommended I open an issue about it.
Game log:
[2021-02-15-1.log](https://github.com/stal111/Forbidden-Arcanus/files/5982520/2021-02-15-1.log)

**Comment by Vaelzan** [comment]
> one of the Valhelsia devs recommended I open an issue about it
That was the Forbidden and Arcanus developer himself asking you. :)

Anyway, it should be a fairly easy fix, it's an unchecked cast to ServerWorld here: https://github.com/stal111/Forbidden-Arcanus/blob/03b0f9579d2a46149a6f08f05566dc9601a4c92c/src/main/java/com/stal111/forbidden_arcanus/item/EdelwoodEntityBucketItem.java#L44

The fix is to literally just swap that line with the line below it (and indent appropriately), so that the placeEntity call is inside the isRemote check.

**Comment by stal111** [comment]
Kinda forgot about this issue but it got fixed now in the new 1.18.1 version. Not sure if I will have the time to backport the fix to 1.16.5 though.
