### ISSUE TITLE
Causes Failure to startup [1.19.2 forge, 43.2.6]

### ISSUE THREAD

**Issue by drakosoldier298** [stal111/Forbidden-Arcanus#332]
**Describe the bug**
HAving this mod in my modpack causes a 6/10 average chance for it to fail to start.
**To Reproduce**
Not fully sure as on some players computers its fine, on the majority it takes 6-10 attempts to get the game to laucn.

**Versions**
 - Forbidden & Arcanus:2.1.1
 - Valhelsia Core:0.5.0
 - Forge:1.19.2 43.2.6

**Additional context**
other player log- https://mclo.gs/54RmmZ6
my log - https://mclo.gs/xZu7zPc

**Comment by drakosoldier298** [comment]
Tested with F&A 2.1.2 Error is even more consistent

**Comment by stal111** [comment]
Could you share the full logs please? They seem to cut at a random time (at least they don't end with any error and I don't see anything related to f&a in them).

From guessing I'd say it's caused by some sort of mod conflict since the 1.19.2 version has been available for quite some time now and is generally pretty well-tested. If something like this was caused by just f&a many players and pack authors would already have complained.

**Comment by drakosoldier298** [comment]
That is the full logs, they dont cut thats just where the game freezes at and refusaes to load any further,
i agree with the fact its likely some mod conflict however its near impossible for me to know what mod would conflict.

**Comment by drakosoldier298** [comment]
from testing it seems the likely conflict is fantasy furnature, or paladins furnature and forbidden and arcanus, as those are the last things to try and load before it freezes permanently.

**Comment by drakosoldier298** [comment]
incompatibility seemingly found.. Bettercombat, Tetra, tetratic combat. 
narrowed down even farther to being just better combat 
https://modrinth.com/mod/better-combat 
5 of 5 test launches without better combat allowed it to launch perfectly.

**Comment by stal111** [comment]
Sorry, but can't really help without a valid crash log that shows the actual error happening.
