### ISSUE TITLE
1.19.2 terra compatibility

### ISSUE THREAD

**Issue by Vallice** [stal111/Forbidden-Arcanus#354]
Hello, 5 month ago the terra:overworld reimagined datapack was release for 1.19.2. It completely changes the biome generation. I've searched for hours to find any sort of cherry or aurum trees or elderwood logs in the world but didn't find any. Apperently they can't spawn in the changed biomes as they should.

**Comment by stal111** [comment]
Aurum trees only generate in Flower Forests and Edelwood trees only in Dark Forests. Are you sure you looked in these biomes specifically?
If they don't generate in these there unfortunately isn't much we can do. Someone would need to provide a compatibility datapack that adds the mods trees to the terra biomes. We won't do it simply because we don't have the time to support all small biome datapacks.
