### ISSUE TITLE
Game crashes when viewing eternal stella smithing recipes [1.19.2]

### ISSUE THREAD

**Issue by zacski1** [stal111/Forbidden-Arcanus#356]
**Describe the bug**
Attempting to view/apply the eternal stella recipes at the smithing table using JEI results in a crash. This only happens when the mod "Create Goggles (Create Plus)" is installed as well.

**To Reproduce**

- Open JEI smithing table recipes tab and attempt to view one including the stella.

OR

- Open the smithing table and attempt to apply an eternal stella manually to any applicable item.

**Expected behavior**
The smithing table recipes in JEI including the stella should be viewable without issue, you should also be able to use the table to physically apply the stella without it crashing.

**Versions**
 - Forbidden & Arcanus: 1.19.2-2.1.3
 - Valhelsia Core: 1.19.2-0.5.0
 - Forge: 43.2.20

**Additional context**
Crash log and full modlist provided below. This has the minimum amount of mods installed to reproduce the issue. 
It appears to be a compatibility issue with Create Goggles as removing the mod has the features working as intended.

https://pastebin.com/vJwwmWTB

**Comment by stal111** [comment]
Please also report this on their issue tracker as this crash needs to be fixed on their side.

The crash occurs because both mods add an item modifier system and both mods store the current modifier in the same NBT tag ("Modifier"). The `getModifier` method in Create Goggles' `ItemModifierManager` tries to get the Eternal modifier from f&a from its registry which doesn't exist there and returns a null value. The methods using the return value cannot work with that null value and crash the game.

Also kinda funny that they nearly fully copied our modifier system.

**Comment by zacski1** [comment]
Aha I had a sneaking suspicion I might have been on the wrong side, small world when code collides. Thanks for taking the time to check and explain the issue as well, I've reported to the Create Goggles dev in hopes it'll be fixed.

Cheers

**Comment by Robocraft999** [comment]
> Also kinda funny that they nearly fully copied our modifier system.

I hope you are ok with that. It was just kind of a backport of an idea with armor trims in 1.20. I really liked the System you had so took it. But yeah, I didn't think about the clash.

**Comment by stal111** [comment]
Yeah it's fine for me. However, at least some credit or notice from where the code originated would be appreciated and is most of the time required by the license. 
That whole modifier system with the custom registry and stuff feels a bit overengineered for your purpose though. A recipe that adds a simple boolean NBT tag (like "HasGoggles") to the item could already be enough.
