### ISSUE TITLE
No ghasts spawning in soulsand valley

### ISSUE THREAD

**Issue by bradreslam** [stal111/Forbidden-Arcanus#383]
There are no ghasts spawning in the soulsand valley with forbidden and arcanus installed.

I flew around in creative for a while and didn't see any ghasts also the ghastfarm I build in the soulsand valley didn't work at all. When I removed forbidden and arcanus ghasts did spawn.

 - Forbidden & Arcanus: 1.20.1-2.2.4
 - Valhelsia Core: 1.1.1
 - Forge: 47.2.0

**Comment by rw-moore** [comment]
I've observed the same problem. It seems to be due to lots of lost souls spawning and rapidly filling the mob cap. A quick and dirty fix is to change LostSoul.canSpawn to return false. This disables all lost souls from spawning naturally everywhere which is not ideal but I've not figured out how to stop it just in Soulsand valleys.

With lost soul spawning disabled ghasts do spawn again and the Nether seems more populated with mobs in general.

**Comment by stal111** [comment]
As of 1.21.1-2.5.8-beta Lost Souls no longer spawn in the Soul Sand Valley biome.
