### ISSUE TITLE
[1.16.1] Won't load on latest version of Forge 

### ISSUE THREAD

**Issue by Gbergz** [stal111/Forbidden-Arcanus#78]
Title^

**Minecraft:** 1.16.1
**Forge:** 32.0.97
**Mod Version:** 1.0-beta-2

Logs: https://hastebin.com/ozowafixup.sql

![image](https://user-images.githubusercontent.com/26634554/88799145-50e23600-d1a6-11ea-8e6e-a58c320615e8.png)

**-** Gbergz

**Comment by GrayParadox** [comment]
Same error. 
![image](https://user-images.githubusercontent.com/68963303/88826639-a5e77180-d1d1-11ea-88a0-5c88cf07d472.png)

Here is a .log file
https://hastebin.com/kiyijaroje.shell

**Comment by JCPlayz777** [comment]
Same, this keeps happening to me, too.

**Comment by Zetabite** [comment]
Forge has yet again made breaking changes, which caused several mods to no longer work. So probably either play with older forge if possible, or disable this mod.

**Comment by xdjoshuaaz** [comment]
Hi @stal111,

I tried looking into this issue with the latest Forge version (.98) but the code in the `1.16` branch doesn't compile after cloning the repo.

However I did decompile the Main.class file in the beta2 JAR, the line that causes the error found in this issue is [here](https://github.com/stal111/Forbidden-Arcanus/blob/ca0a8e4c41222da946e47dafc37b0d154055f371/src/main/java/com/stal111/forbidden_arcanus/Main.java#L97)
```
public Main() {
    ...
    modEventBus.addListener(this::serverAboutToStart);
    ...
}
```

This registers the `serverAboutToStart` method to the mod event bus, which is incorrect as `FMLServerAboutToStartEvent` doesn't implement the `IModBusEvent` interface hence the error in this issue's crash report. 

Removing this line of code with a Java decompiler let the mod boot up in my Forge 32.0.98 installation.

While I can't test/verify that this method is still called when the server boots up (no debugger), it should continue to work as `MinecraftForge.EVENT_BUS.register(this);` is called which will find all `@SubscribeEvent` methods and register them to the Forge event bus where this event actually fires ([Forge source here](https://github.com/MinecraftForge/MinecraftForge/blob/638d1d31deabd8a83cf4b84496549703bc527ab4/src/main/java/net/minecraftforge/fml/server/ServerLifecycleHooks.java#L98))

Hope this helps.
Josh

**Comment by stal111** [comment]
Thanks for looking into it :) The serverAboutToStart method could be completly removed as it is no longer needed (Forge added a AddReloadListenerEvent), but I dont think that was the problem as it always worked that way. The real problem I saw when updating was that Forge removed some methods like isBeaconBase() or isBeaconPayment() as they're now handled through tags.
