### ISSUE TITLE
[1.15.2] bucket seems to use wrong fluid handler

### ISSUE THREAD

**Issue by Terpo** [stal111/Forbidden-Arcanus#92]
I just copy the text from my issue into yours. Some more details can be found here: https://github.com/Terpo/Waterworks/issues/80

___
there is a bug, if i use elden wood bucket of forbidden arcanus in a wood rain collector or normal rain collector or on controller you give me a vanilla water bucket

minecraft 1.15.2
forge-31.2.33
forbidden_arcanus-1.15.2-1.5
waterworks-1.15.2-2.1.2

___

**Comment by IceDragon200** [comment]
I'd like to add, if the edelwood bucket is used in a Traveler's Backpack it also returns an Vanilla Bucket instead of an empty Edelwood bucket

I originally reported this over at their tracker, but was notified it's likely an issue over here (see https://github.com/Tiviacz1337/Travelers-Backpack/issues/160#issuecomment-691641539)

**Comment by stal111** [comment]
Should be fixed in 16.2.0
