### ISSUE TITLE
Cannot deny users the right to redistribute the mod

### ISSUE THREAD

**Issue by adri326** [stal111/Forbidden-Arcanus#96]
(I am not a lawyer and may be wrong)

The [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus) of this mod explicitly denies users who get a copy of this mod their right to publicly redistribute it:

> **Do NOT:**
> - Re-upload the mod / data pack file on other websites, if so, first ask CesarZorak or Stal.

However, this mod is [distributed](https://github.com/stal111/Forbidden-Arcanus/blob/1.16/LICENSE.txt) under [LGPLv2.1](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html), which states that anyone may copy and redistribute this mod's source code:

> 1. You may copy and distribute verbatim copies of the Library's complete source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice and disclaimer of warranty; keep intact all the notices that refer to this License and to the absence of any warranty; and distribute a copy of this License along with the Library.

Moreover, one may make a copy of this code, relicense it under GPLv3 and freely distribute its binaries under the terms of GPLv3.

I am personally against denying holders of the binaries their right to redistribute it, so I would suggest you would remove the notice on the CurseForge page.

**Comment by stal111** [comment]
Thats just the Forge License which I didnt delete from the project. Currently the mod is licensed under All Rights Reserved which isnt optimal either, so I will probably change the license soon.

**Comment by andrewsf** [comment]
To reinforce @stal111's conclusion, these two critical sections from LICENSE.txt:

> Unless noted below, Minecraft Forge, Forge Mod Loader, and all 
parts herein are licensed under the terms of the LGPL 2.1

> A note on infectivity:
The LGPL is chosen specifically so that projects may depend on Forge
features without being infected with its license. That is the 
purpose of the LGPL. Mods and others using this code via ordinary
Java mechanics for referencing libraries are specifically not bound
by Forge's license for the Mod code.

I think these bits are baking in an incorrect assumption (emphasis mine):
> denies users who get a copy of this mod **their right** to publicly redistribute it

> denying holders of the binaries **their right** to redistribute it

Hopefully an updated license should clear everything up for good.
